/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.meltzg.fs;

import lombok.Data;

@Data
public class Library {
    static {
        System.loadLibrary("jmtp");
    }

    private native int foo();

    private int foo;

    public int someLibraryMethod() {
        return foo() * foo;
    }
}
