/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.meltzg.fs;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertEquals("someLibraryMethod should return '4'", 4, classUnderTest.someLibraryMethod());
    }
}
