/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.meltzg.fs;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        classUnderTest.setFoo(4);
        for (var i = 0; i < 3; i++) {
            assertEquals("someLibraryMethod should return 'i'", i * classUnderTest.getFoo(), classUnderTest.someLibraryMethod());
        }
    }
}
